### ISSUE TITLE
UI/UX Issues

### ISSUE THREAD

**Issue by frasermcc9** [SE701-T5/frontend#85]
There are some UI and UX issues with the app to clean up. @ShenaeA will create a list of problems and reply with them to this issue.

We will be fixing 
- Mobile View
- Desktop View

**Comment by kaylward** [comment]
This is what I've found so far:

Issues Between Pages:
- [x] Differences in the white underline. e.g. under "Popular Communities" vs "Popular Posts". It also changes depending on the zoom of the page -> notice the gap. Change to be a fill rather than a border? believe it's hp.Divider.
- [x] Colour for "NEW COMMUNITY" on /community and "NEW POST" on /posts buttons are different colours, change to be #4f72aa as the current colours seem to be random. 
- [x] Title placement on all pages, make the same as where "Posts" is placed.
- [ ] Remove drop-down from profiles, instead, the "PROFILES" button should do what the dropdown does.

/posts:
On a post:
- [x] Transitions between photos. Realistically, multiple photos should be presented in magazine-style, but for simplicity purposes, can just change so arrows are visible at all times rather than by mouse over. (changed to keep previous mouse over design, but added thumbnails below)
- [x] Remove the "1 out of 2" from the images. the current appearance is similar to something you'd see on some type of malware-infected ad.
- [x] Up/down arrows should change colour if the user has selected one (this includes on the comments page).
- [x] Idk if this can be fixed, but there's a vertical pixel shift when the photos slide across, (up and down quite quickly). The number of votes jumps too. scroll to about halfway through the image to see it.
- [x] Remove link symbol and the underline/colour change from . Instead clicking anywhere on the description, title etc (everywhere except the photo) should bring the user to the post page.
- [x] The community name text (top left of post) should be the same size font as the username/timestamp text
- [x] All text should be black on the post (timestamp, username and community name
- [x] Comment button changed to colour #4f72aa

/communities:
- [x] Search has "Search Posts" not "Search Communities" and text is not aligned to the middle, slightly offset vertically.
- [x] Depending on screen size, the tiles change vertically. One solution would be to have a vertical and landscape design, so once the browser width becomes too small it changes to the vertical presentation (see pdf on drive Assignment 2/communities-frames.pdf).

/login
- [x] see pdf on drive Assignment 2/login-page.pdf

Contact @ShenaeA if anything is unclear
